name: Simple CI

on:
  push:
    branches:
      - main
env:
  APP_NAME: pipeline-test
  ENVIRONMENT: dev
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display Files
        run: ls -la

      - name: Print Date
        run: date
      
      - name: Print Working Directory
        run: pwd

      - name: print app name
        run: echo $APP_NAME

      - name: print env
        run: echo $ENVIRONMENT
